# param1:
#   GET: file1
#   POST: file2
#   param2:
#     GET: file4
#     POST: file5
#     param3:
#        GET: file6
#
#method "POST", "GET", "PUT", "DELETE""


GET: templates/template.php
xhr:
  GET: partials/products/index.php

products:
  GET: templates/template.php
  xhr:
    GET: partials/products/index.php

recruit:
  GET: templates/template.php
  xhr:
    GET: partials/recruit/index.php

about:
  GET: templates/template.php
  xhr:
    GET: partials/about/index.php

contact:
  GET: templates/template.php
  POST: action/contact/post.php
  xhr:
    GET: partials/contact/index.php

alcCalc:
  GET: partials/alcCalc/index.php

#2_5dbutton:
#  GET: partials/2_5dbutton/index.php
#  create:
#    POST: action/2_5dbutton/create_button.php

en:
  alcCalc:
    GET: partials/alcCalc/index_en.php

errors:
  404:
    GET: partials/errors/404.php
