name: Netlify

on:
  push:
    branches:
      - master
      - staging

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.15.1]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v
      - run: yarn install
      - run: yarn generate
        env:
          SITE_RECAPTCHA_KEY: ${{ secrets.SITE_RECAPTCHA_KEY }}
          SITE_RECAPTCHA_SECRET: ${{ secrets.SITE_RECAPTCHA_SECRET }}

      # Netlifyにデプロイする
      - run: yarn netlify deploy --dir=.output/public --branch=staging
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
